# Generated by Django 3.1.1 on 2020-09-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
