# Generated by Django 3.1.1 on 2020-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_remove_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
