# Generated by Django 3.1.1 on 2020-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_auto_20200930_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='postal_zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
